name: macOS

on:
  push:
    branches: [ main, 'v[0-9]+.x' ]
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: clang++ C++11
            cxx_compiler: clang++
            cxx_standard: 11
            cmake_options: ""

          - name: clang++ C++17
            cxx_compiler: clang++
            cxx_standard: 17
            cmake_options: ""

    steps:
    - uses: actions/checkout@v4
    - name: get test data
      run: test/download-tests.sh
    - name: cmake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.cmake_options }}
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: ctest --test-dir build -C Release -V
    - name: after test
      if: ${{ matrix.after_test }}
      run: ${{ matrix.after_test }}
